import { create } from "zustand";

/**
 * Zustand store for managing the application's global state.
 * Currently focuses on tracking recently created videos and their statuses.
 */
export const useFlickzoStore = create<{
  // List of videos recently generated by the user
  recentVideos: {
    id: string;
    title: string;
    status: string;
    [key: string]: unknown;
  }[];
  // Action to initialize or update the entire list of recent videos
  setRecentVideos: (
    videos: {
      id: string;
      title: string;
      status: string;
      [key: string]: unknown;
    }[]
  ) => void;
  // Action to remove a specific video from the store (e.g., after deletion)
  removeVideo: (videoId: string) => void;
}>((set) => ({
  recentVideos: [],
  setRecentVideos: (videos) => set({ recentVideos: videos }),
  removeVideo: (videoId) =>
    set((state) => ({
      recentVideos: state.recentVideos.filter((v) => v.id !== videoId),
    })),
}));
